- name: Ensure bitwardenrs system group
  group:
    name: bitwardenrs
    system: yes
    state: present

- name: Ensure bitwardenrs system user
  user:
    name: bitwardenrs
    group: bitwardenrs
    home: "{{ bitwardenrs_directory }}"
    create_home: yes
    move_home: yes
    password: '!'
    system: yes
    shell: /bin/sh
    comment: Bitwarden_RS server,,,
    state: present

- name: Install required build-packages
  package:
    name: "{{ _bitwardenrs_build_packages }}"
    state: present

- name: Get rustup installer
  get_url:
    url: https://sh.rustup.rs
    dest: ~bitwardenrs/rustup.sh
    owner: bitwardenrs
    group: bitwardenrs

- name: Install rust nightly
  command: su bitwardenrs -c '/bin/sh ~bitwardenrs/rustup.sh --no-modify-path --default-toolchain nightly -y'
  register: _bitwardenrs_install_rust_nightly
  changed_when: "'nightly installed' in _bitwardenrs_install_rust_nightly.stdout"

- name: Download bitwarden_rs repo
  unarchive:
    src: "https://github.com/dani-garcia/bitwarden_rs/archive/{{ bitwardenrs_version }}.tar.gz"
    dest: "{{ bitwardenrs_directory }}"
    creates: "{{ bitwardenrs_directory }}/bitwarden_rs-{{ bitwardenrs_version }}"
    remote_src: yes
    owner: bitwardenrs
    group: bitwardenrs

- name: Compile bitwarden_rs
  command:
    cmd: su bitwardenrs -c '~bitwardenrs/.cargo/bin/cargo build --features {{ bitwardenrs_build_backend }} --release'
    chdir: "{{ bitwardenrs_directory }}/bitwarden_rs-{{ bitwardenrs_version }}"
    creates: "{{ omit if bitwardenrs_force_recompile else creates }}"
  vars:
    creates: "{{ bitwardenrs_directory }}/bitwarden_rs-{{ bitwardenrs_version }}/target/release/bitwarden_rs"

- name: Copy bitwarden_rs executable
  copy:
    src: "{{ bitwardenrs_directory }}/bitwarden_rs-{{ bitwardenrs_version }}/target/release/bitwarden_rs"
    dest: "{{ bitwardenrs_directory }}/bitwarden_rs"
    remote_src: yes
    mode: preserve
    owner: bitwardenrs
    group: bitwardenrs
  notify: Restart bitwardenrs

- name: Download patched bitwarden webvault
  unarchive:
    src: https://github.com/dani-garcia/bw_web_builds/releases/download/v{{ bitwardenrs_webvault_version }}/bw_web_v{{ bitwardenrs_webvault_version }}.tar.gz
    dest: "{{ bitwardenrs_directory }}"
    remote_src: yes
    owner: bitwardenrs
    group: bitwardenrs
  when: bitwardenrs_webvault|bool

- name: Create datadir
  file:
    path: "{{ bitwardenrs_datadir }}"
    state: directory
    owner: bitwardenrs
    group: bitwardenrs
